### ISSUE TITLE
Types support for clone-buffer

### ISSUE THREAD

**Issue by tanvirrb** [gulpjs/clone-buffer#4]
```TS7016: Could not find a declaration file for module 'clone-buffer'. '/path/to/module/ts-test/node_modules/clone-buffer/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/clone-buffer` if it exists or add a new declaration (.d.ts) file containing `declare module 'clone-buffer';```

Is there any ***type-support*** for **TypeScript** for clone-buffer? I searched rigorously but couldn't found any. If not, is there any plan to add it in near future?

**Comment by phated** [comment]
Historically, we've not provided TS definitions. Sometimes we accept drive-by contributions of them, but those people never stay around to keep them up-to-date.

It's probably best for someone to contribute them to the `@types` repo
